apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dotnet-basic-viybhmvl
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/dotnet-basic-viybhmvl:393584a6133f06d241816b6df4f799a498c3c796@sha256:4a6b7ffbc559eefe48a3d5759f9de774fe5f0340181edf357b4beb797916ebcb
          name: container-image
